# Generated by Django 4.2.7 on 2023-11-14 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motel',
            old_name='modelo',
            new_name='dirrecion',
        ),
    ]
