# Generated by Django 4.2.7 on 2023-11-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_modelo_motel_dirrecion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name_room',
            field=models.CharField(max_length=500),
        ),
    ]
